name: Build OpenAppFilter ARM64 ipk

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest   # 免费 x86_64  runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-setuptools \
            python3-dev rsync subversion swig time xsltproc zlib1g-dev

      - name: Download OpenWrt SDK (ARM64)
        run: |
          wget -q https://downloads.openwrt.org/releases/22.03.5/targets/armvirt/64/openwrt-sdk-22.03.5-armvirt-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Update feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Insert OpenAppFilter source
        run: |
          cd sdk
          git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter

      - name: Configure & build
        run: |
          cd sdk
          # 非交互：已默认 ARM64 + 选中 luci-app-oaf
          make defconfig
          make package/luci-app-oaf/compile V=s -j$(nproc)

      - name: Upload ipk artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openappfilter-arm64-ipk
          path: sdk/bin/packages/*/luci/*.ipk
