name: Build OpenAppFilter native ARM64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  native-arm64:
    runs-on: ubuntu-24.04-arm   # 原生 ARM64 VM
    steps:
      - uses: actions/checkout@v4

      - name: Install deps & build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential make git ncurses-dev libssl-dev \
            wget unzip python3 python3-setuptools
          git clone https://github.com/destan19/OpenAppFilter.git
          echo "CONFIG_PACKAGE_luci-app-oaf=y" >>.config  
          make defconfig 
          make package/luci-app-oaf/compile V=s  
          make package/open-app-filter/compile V=s
          make package/oaf/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openappfilter-native-arm64
          path: OpenAppFilter/*.ipk
