jobs:
  native-arm64:
    runs-on: ubuntu-24.04-arm   # 原生 ARM64 VM
    steps:
      - uses: actions/checkout@v4
      - name: Install deps & build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git ncurses-dev libssl-dev \
            wget unzip python3
          git clone https://github.com/destan19/OpenAppFilter.git
          cd OpenAppFilter
          make
      - uses: actions/upload-artifact@v4
        with:
          name: openappfilter-native-arm64
          path: OpenAppFilter/*.ipk
