name: Build OpenAppFilter ARM64 ipk

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest   # 免费 x86_64  runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-setuptools \
            python3-dev rsync subversion swig time xsltproc zlib1g-dev

      - name: Download OpenWrt SDK (ARM64)
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.0/targets/armvirt/64/immortalwrt-sdk-24.10.0-armvirt-64_gcc-13.3.0_musl.Linux-x86_64.tar.xz
          tar -xf immortalwrt-sdk-*.tar.xz
          mv immortalwrt-sdk-24.10.0-armvirt-64_gcc-13.3.0_musl.Linux-x86_64 sdk

      - name: Update feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Insert OpenAppFilter source
        run: |
          cd sdk
          git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter

      - name: Configure & build
        run: |
          cd sdk
          # 非交互：已默认 ARM64 + 选中 luci-app-oaf
          make defconfig
          make package/luci-app-oaf/compile V=s -j$(nproc)

      # - name: Upload ipk artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: openappfilter-arm64-ipk
      #     path: sdk/bin/packages/*/luci/*.ipk
      - name: Find and collect IPK files
        run: |
          cd sdk
          # 创建输出目录
          mkdir -p ../artifacts
          # 查找所有相关的IPK文件
          find . -name "*oaf*.ipk" -o -name "*appfilter*.ipk" | while read ipk; do
            echo "Found IPK: $ipk"
            cp "$ipk" ../artifacts/
          done
          # 如果没找到，尝试标准位置
          if [ ! -f ../artifacts/*.ipk ]; then
            cp bin/packages/*/base/*oaf*.ipk ../artifacts/ 2>/dev/null || true
            cp bin/packages/*/luci/*oaf*.ipk ../artifacts/ 2>/dev/null || true
          fi
          # 列出找到的文件
          echo "Collected artifacts:"
          ls -la ../artifacts/ || echo "No artifacts found"

      - name: Upload ipk artifacts
        if: success() || failure()  # 即使编译失败也上传已找到的文件
        uses: actions/upload-artifact@v4
        with:
          name: openappfilter-arm64-ipk
          path: artifacts/*.ipk
          if-no-files-found: warn  # 如果没有文件，警告而不是失败

      - name: Debug info (on failure)
        if: failure()
        run: |
          cd sdk
          echo "=== Debug information ==="
          echo "Current directory: $(pwd)"
          echo "Package directory contents:"
          ls -la package/ 2>/dev/null || echo "No package directory"
          echo "Feeds directory contents:"
          ls -la feeds/ 2>/dev/null || echo "No feeds directory"
          echo "OpenAppFilter directory:"
          ls -la package/openappfilter/ 2>/dev/null || echo "No openappfilter directory"
          echo "Config contents:"
          grep -i "oaf\|appfilter" .config 2>/dev/null || echo "No relevant config found"
